from django.db import models
from django import forms
from django.forms import ModelForm

class Train(models.Model):

  city_name = models.CharField(max_length=50)
  citypop = models.IntegerField(default=0, blank=True)
  miles_of_city = models.IntegerField(default=0, blank=True)
  system_length = models.IntegerField(default=0, blank=True)
  riders_per_yr = models.IntegerField(default=0, blank=True)
  cost_tix = models.IntegerField(default=0, blank=True)
  key_facts = models.CharField(max_length=500, blank=True)
  numb_stations = models.IntegerField(default=0, blank=True)
  year_opened = models.IntegerField(default=0, blank=True)
  


class TrainForm(ModelForm):
  """A chart for our train info"""
  class Meta:
    model = Train

#foreign key references another table via a number code (generated by computer, 

#primary key means whatever column you want to search by -- you can tell 
# the computer which column you want as the primary key
# but usually in django you want to let django set it because pks need to be unique

